[theme]
base="dark"
primaryColor="#000000"
backgroundColor="#282828"
secondaryBackgroundColor="#1e1e1e"
celloneBackgroundColor="#7e7e7e"
textColor="#ffffff"
RAPIDAPI_KEY = "1ce12aafcdmshdb6eea1ac608501p1ab501jsn4a47cc5027ce"
